Add support for defaulted methods
rust-lang/impl-trait-utils pull request #20
Opened 2023-12-27 15:24 UTC by mendess

Resolves #17

2023-12-29 16:28 UTC, compiler-errors requested changes

2023-12-29 16:28 UTC, compiler-errors commented on trait-variant/src/variant.rs
> +    // if there is a defaulted method, than that defaulted method has a bound of Self: Sync,
This is not really true -- `Self: Sync` is only needed because `&self` is one of the arguments to the function. I believe the correct approach would be to take the receiver -- whether it be `&self`, `&mut self`, or `self`, and bound the type of the receiver by `: Send`.

This works out because `&Self: Send` only if `Self: Sync`.

Also, I believe that these bounds should be placed on the specific methods that require them, not on the `impl` itself.

2023-12-29 16:28 UTC, compiler-errors commented on trait-variant/src/variant.rs
> +                .map(|b| syn::parse2(quote! { { async move #b } }).unwrap()),
Just noting that the correct desugaring would involve moving every argument into the block as well.

2023-12-29 19:37 UTC, mendess commented
@compiler-errors so I gave your suggestions a try with these modifications to the example trait
```rs
#[trait_variant::make(IntFactory: Send)]
pub trait LocalIntFactory {
    const NAME: &'static str;

    type MyFut<'a>: Future
    where
        Self: 'a;

    async fn make(&self, x: u32, y: &str) -> i32;
    async fn make_mut(&mut self);
    fn stream(&self) -> impl Iterator<Item = i32>;
    fn call(&self) -> u32;
    fn another_async(&self, input: Result<(), &str>) -> Self::MyFut<'_>;
    async fn defaulted(&self) -> i32 {
        self.make(10, "10").await
    }
    async fn defaulted_mut(&mut self) -> i32 {
        self.make(10, "10").await
    }
    async fn defaulted_mut_2(&mut self) {
        self.make_mut().await
    }
    async fn defaulted_move(self) -> i32
    where
        Self: Sized,
    {
        self.make(10, "10").await
    }
}
```
And I generated something like this
```rs
pub trait IntFactory: Send {
    const NAME: &'static str;
    type MyFut<'a>: Future
    where
        Self: 'a;
    fn make(&self, x: u32, y: &str) -> impl ::core::future::Future<Output = i32> + Send;
    fn make_mut(&mut self) -> impl ::core::future::Future<Output = ()> + Send;
    fn stream(&self) -> impl Iterator<Item = i32> + Send;
    fn call(&self) -> u32;
    fn another_async(&self, input: Result<(), &str>) -> Self::MyFut<'_>;
    fn defaulted<'the_self_lt>(&'the_self_lt self) -> impl ::core::future::Future<Output = i32> + Send
    where
        &'the_self_lt Self: Send,
    {
        async { self.make(10, "10").await }
    }
    fn defaulted_mut<'the_self_lt>(&'the_self_lt mut self) -> impl ::core::future::Future<Output = i32> + Send
    where
        &'the_self_lt mut Self: Send, // error[E0277]: `Self` cannot be shared between threads safely
    {
        async { self.make(10, "10").await }
    }
    fn defaulted_mut_2<'the_self_lt>(&'the_self_lt mut self) -> impl ::core::future::Future<Output = ()> + Send
    where
        &'the_self_lt mut Self: Send,
    {
        async { self.make_mut().await }
    }
    fn defaulted_move(self) -> impl ::core::future::Future<Output = i32> + Send
    where
        Self: Sized,
        Self: Send, // error[E0277]: `Self` cannot be shared between threads safely
    {
        async { self.make(10, "10").await }
    }
}
```
The errors are because the `async` block of those particular default implementations don't "capture" `self` the same way the `method` does. For example, `default_mut` doesn't actually need `&mut self` for it's implementation. Hence the compiler requires `Self: Sync`.

Do you still think it's worth trying to generate very precise bounds like I tried to do here?

2023-12-29 22:09 UTC, andrewtoth commented
@mendess I believe in your generated example you are missing the `move` keyword after `async`. Using `async move {...}` fixes the compiler warnings.

2023-12-30 12:49 UTC, mendess commented
@andrewtoth I remove the `move` keyword of what @compiler-errors mentioned, but maybe I'm misunderstood them

2023-12-30 13:54 UTC, compiler-errors commented
I didn't mention removing the move keyword--that is definitely needed.

2024-01-01 13:35 UTC, mendess commented
Alright, edited the codegen to have more precise bounds for Self

This is what it looks like now
```rs
use std::future::Future;

#[allow(async_fn_in_trait)]
pub trait LocalIntFactory {
    const NAME: &'static str;

    type MyFut<'a>: Future
    where
        Self: 'a;

    async fn make(&self, x: u32, y: &str) -> i32;
    async fn make_mut(&mut self);
    fn stream(&self) -> impl Iterator<Item = i32>;
    fn call(&self) -> u32;
    fn another_async(&self, input: Result<(), &str>) -> Self::MyFut<'_>;
    async fn defaulted(&self) -> i32 {
        self.make(10, "10").await
    }
    async fn defaulted_mut(&mut self) -> i32 {
        self.make(10, "10").await
    }
    async fn defaulted_mut_2(&mut self) {
        self.make_mut().await
    }
    async fn defaulted_move(self) -> i32
    where
        Self: Sized,
    {
        self.make(10, "10").await
    }
}
pub trait IntFactory: Send {
    const NAME: &'static str;
    type MyFut<'a>: Future
    where
        Self: 'a;
    fn make(&self, x: u32, y: &str) -> impl ::core::future::Future<Output = i32> + Send;
    fn make_mut(&mut self) -> impl ::core::future::Future<Output = ()> + Send;
    fn stream(&self) -> impl Iterator<Item = i32> + Send;
    fn call(&self) -> u32;
    fn another_async(&self, input: Result<(), &str>) -> Self::MyFut<'_>;
    fn defaulted<'the_self_lt>(
        &'the_self_lt self,
    ) -> impl ::core::future::Future<Output = i32> + Send
    where
        &'the_self_lt Self: Send,
    {
        async move { self.make(10, "10").await }
    }
    fn defaulted_mut<'the_self_lt>(
        &'the_self_lt mut self,
    ) -> impl ::core::future::Future<Output = i32> + Send
    where
        &'the_self_lt mut Self: Send,
    {
        async move { self.make(10, "10").await }
    }
    fn defaulted_mut_2<'the_self_lt>(
        &'the_self_lt mut self,
    ) -> impl ::core::future::Future<Output = ()> + Send
    where
        &'the_self_lt mut Self: Send,
    {
        async move { self.make_mut().await }
    }
    fn defaulted_move(self) -> impl ::core::future::Future<Output = i32> + Send
    where
        Self: Sized,
        Self: Send,
    {
        async move { self.make(10, "10").await }
    }
}
impl<T> LocalIntFactory for T
where
    T: IntFactory,
    Self: Sync // this is only added if there are defaulted methods
{
    const NAME: &'static str = <Self as IntFactory>::NAME;
    type MyFut<'a> = <Self as IntFactory>::MyFut<'a> where Self: 'a;
    async fn make(&self, x: u32, y: &str) -> i32 {
        <Self as IntFactory>::make(self, x, y).await
    }
    async fn make_mut(&mut self) {
        <Self as IntFactory>::make_mut(self).await
    }
    fn stream(&self) -> impl Iterator<Item = i32> {
        <Self as IntFactory>::stream(self)
    }
    fn call(&self) -> u32 {
        <Self as IntFactory>::call(self)
    }
    fn another_async(&self, input: Result<(), &str>) -> Self::MyFut<'_> {
        <Self as IntFactory>::another_async(self, input)
    }
    async fn defaulted(&self) -> i32 {
        <Self as IntFactory>::defaulted(self).await
    }
    async fn defaulted_mut(&mut self) -> i32 {
        <Self as IntFactory>::defaulted_mut(self).await
    }
    async fn defaulted_mut_2(&mut self) {
        <Self as IntFactory>::defaulted_mut_2(self).await
    }
    async fn defaulted_move(self) -> i32
    where
        Self: Sized,
    {
        <Self as IntFactory>::defaulted_move(self).await
    }
}```

2024-01-03 15:54 UTC, mendess commented on trait-variant/src/variant.rs
> +    let self_is_sync = tr
![image](https://github.com/rust-lang/impl-trait-utils/assets/19352680/dcf9a4e9-f072-4d1e-8a21-f9c86f4ec690)
It is still needed. This is for the blanket impl, if there are defaulted methods in the trait they basically require `Self: Sync` so in order for the impl to be valid it can only "blanket" over types that are `Sync`

2024-01-03 16:39 UTC, mendess commented on trait-variant/src/variant.rs
> +                .map(|b| syn::parse2(quote! { { async move #b } }).unwrap()),
Added a commit that does this. Sorry for misunderstanding the original comment

2024-01-04 18:09 UTC, andrewtoth commented on trait-variant/src/variant.rs
> +    let self_is_sync = tr
I see, but it would make more sense to add to add the bound `for<'a> &'a Self: Send`, which is what the compiler is complaining about?
Also, not sure why the it complains about only about the `defaulted(&self)` function and not the `default_mut(&mut  self)` functions?

2024-01-15 10:52 UTC, ryo33 commented on trait-variant/src/variant.rs
> +                    .expect("valid async block")
Though I'm not confident, using `parse_quote` instead seems idiomatic in this case.

```rust
parse_quote! { { async move { #(#items)* #block} } }
```

2024-01-16 13:29 UTC, mendess commented on trait-variant/src/variant.rs
> +    let self_is_sync = tr
I'm not sure what the difference is, maybe there is some implied bound? :thinking:

2024-01-16 13:30 UTC, mendess commented
Edited the codegen again and this is what it looks like now
```rs
impl<TraitVariantBlanketType> LocalIntFactory for TraitVariantBlanketType
where
    TraitVariantBlanketType: IntFactory,
    for<'s> &'s Self: Send, // no longer bounds `Self: Sync`
{
    const NAME: &'static str = <Self as IntFactory>::NAME;
    type MyFut<'a> = <Self as IntFactory<>>::MyFut<'a> where Self: 'a;
    async fn make(&self, x: u32, y: &str) -> i32 {
        <Self as IntFactory>::make(self, x, y).await
    }
    async fn make_mut(&mut self) {
        <Self as IntFactory>::make_mut(self).await
    }
    fn stream(&self) -> impl Iterator<Item = i32> {
        <Self as IntFactory>::stream(self)
    }
    fn call(&self) -> u32 {
        <Self as IntFactory>::call(self)
    }
    fn another_async(&self, input: Result<(), &str>) -> Self::MyFut<'_> {
        <Self as IntFactory>::another_async(self, input)
    }
    async fn defaulted(&self, x: u32) -> i32 {
        <Self as IntFactory>::defaulted(self, x).await
    }
    async fn defaulted_mut(&mut self) -> i32 {
        <Self as IntFactory>::defaulted_mut(self).await
    }
    async fn defaulted_mut_2(&mut self) {
        <Self as IntFactory>::defaulted_mut_2(self).await
    }
    async fn defaulted_move(self) -> i32
    where
        Self: Sized,
    {
        <Self as IntFactory>::defaulted_move(self).await
    }
}
```

2024-02-14 12:46 UTC, sargarass commented
@mendess can you please rebase it onto new main.

2024-02-14 23:08 UTC, mendess commented
@sargarass Done!

2024-02-27 14:36 UTC, mendess commented
@compiler-errors could I get a re-review? Maybe get this merged? :eyes:

2024-03-05 14:07 UTC, sargarass commented
@tmandry could you also take a look? We are using the Mendess branch in our closed-source project and would like to have it merged.

2024-03-05 16:25 UTC, ryo33 approved these changes

2024-03-18 23:23 UTC, tmandry requested changes
Thanks, I looked it over. I think I'd rather require that the needed bounds are _already_ listed on the trait itself than silently add them to individual methods. My goal is for uses/expansions of this macro to eventually be replaced with trait aliases. It isn't possible to have a trait alias that adds where clauses to individual methods.

For the common case of `Send` bounds, we can require that `Sync` is also listed. In the general case, we unfortunately can't check for the user and will have to let the compiler give an error on the generated code. (Once `#[diagnostic::on_unimplemented]` is stabilized in the next release I think we can do something clever with that to improve the user experience, in the general case.)

2024-03-18 23:23 UTC, tmandry commented on trait-variant/src/variant.rs
> +        blanket_where_clause.push(parse_quote! { for<'s> &'s Self: Send });
Here and below: This assumes the user is using `Send` as a bound, but the macro is designed to be more general than that. I don't have a problem with special casing `Send` to provide a better user experience, but we cannot just assume that's what the bound is.

2024-03-25 03:16 UTC, loichyan commented
I tested this PR and found that calling an async function that returns a static reference in the defaulted method leads to a compilation error:

```rust
#[trait_variant::make(MyTrait: Send)]
// 1. lifetime may not live long enough
//    returning this value requires that `'the_self_lt` must outlive `'static`
// 2. implementation of `std::marker::Send` is not general enough
//    `&'0 Self` must implement `std::marker::Send`, for any lifetime `'0`...
//    ...but `std::marker::Send` is actually implemented for the type `&'the_self_lt Self`
// 3. to declare that `impl std::future::Future<Output = i32> + std::marker::Send` captures data from argument `self`, you can add an explicit `'the_self_lt` lifetime bound: ` + 'the_self_lt`
// 4. lifetime `'the_self_lt` defined here
pub trait LocalMyTrait {
    async fn make(&self, x: u32, y: &str) -> i32;

    async fn defaulted_with_static(&self, x: u32, y: &str) -> i32 {
        let _t = get_global_var().await;
        self.make(x, y).await
    }
}

async fn get_global_var() -> &'static i32 {
    todo!()
}
```

The expanded code:

```rust
#[allow(async_fn_in_trait)]
pub trait LocalMyTrait {
    async fn make(&self, x: u32, y: &str) -> i32;
    async fn defaulted_with_static(&self, x: u32, y: &str) -> i32 {
        let _t = get_global_var().await;
        self.make(x, y).await
    }
}
pub trait MyTrait: Send {
    fn make(&self, x: u32, y: &str) -> impl ::core::future::Future<Output = i32> + Send;
    fn defaulted_with_static<'the_self_lt>(
        &'the_self_lt self,
        x: u32,
        y: &str,
    ) -> impl ::core::future::Future<Output = i32> + Send // Add 'the_self_lt bound here, it compiles
    where
        &'the_self_lt Self: Send,
    {
        async move {
            let __self = self;
            let x = x;
            let y = y;
            {
                let _t = get_global_var().await;
                __self.make(x, y).await
            }
        }
    }
}
impl<TraitVariantBlanketType: MyTrait> LocalMyTrait for TraitVariantBlanketType
where
    for<'s> &'s Self: Send,
{
    async fn make(&self, x: u32, y: &str) -> i32 {
        <Self as MyTrait>::make(self, x, y).await
    }
    async fn defaulted_with_static(&self, x: u32, y: &str) -> i32 {
        <Self as MyTrait>::defaulted_with_static(self, x, y).await
    }
}
```

2024-03-25 06:42 UTC, loichyan commented
It also results in a lifetime mismatch error when overriding the default method:

```rust
#[trait_variant::make(MyTrait: Send)]
pub trait LocalMyTrait {
    async fn defaulted(&self, _x: u32, _y: &str) -> i32 {
        todo!()
    }
}

struct MyImpl;

impl MyTrait for MyImpl {
    // 1. lifetime parameters or bounds on method `defaulted` do not match the trait declaration
    // lifetimes do not match method in trait [E0195]
    async fn defaulted(&self, _x: u32, _y: &str) -> i32 {
        todo!()
    }
}
```

2024-03-25 07:54 UTC, loichyan commented
> ... an async function that returns a static reference in the defaulted method leads to a compilation error
> It also results in a lifetime mismatch error when overriding the default method

A possible solution for the two issues is to replace the `&'the_self_lt Self: Send` bound with `Self: Sync`.

2024-04-29 14:17 UTC, Sytten commented
Any movement?

2024-07-30 00:20 UTC, tmandry commented
> A possible solution for the two issues is to replace the `&'the_self_lt Self: Send` bound with `Self: Sync`.

That is one way, and might lead to better error messages in the `Send` case specifically.

In the general case we can replace `&'the_self_lt Self: Send` with `for<'a> &'a Self: Send` and it seems to work.

2026-06-26 18:01 UTC, closed without merging